on:
  push:
    branches: ["none"]
name: Snap
permissions:
  id-token: write
  contents: read
jobs:
  snap:
    name: "Test if the Snap can be built from the latest commit in the branch"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      - name: Build Snap
        uses: snapcore/action-build@v1
        id: snapcraft-build
        with:
          snapcraft-args: "-v"
      - uses: actions/upload-artifact@v3
        with:
          name: ascii-draw-amd64-snap
          path: ${{ steps.snapcraft-build.outputs.snap }}
      - name: Upload and release Ascii Draw snap with every changes
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.snapcraft-build.outputs.snap }}
          release: ${{'edge'}}
